### ISSUE TITLE
Duplicate __builtin_clz symbols on MSVC Windows

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/compiler-builtins#167]
This is due to the fact that [their definition](https://github.com/llvm-mirror/compiler-rt/blob/bc311bbb04f823ee9d58261111a4455a0354c358/lib/builtins/int_lib.h#L92-L127) is not marked `static`. Filing an issue to track this, gonna add a FIXME for now.

**Comment by alexcrichton** [comment]
I opened an [upstream diff](https://reviews.llvm.org/D34599) for this.

**Comment by AaronKutch** [comment]
What's the status on this?
