### ISSUE TITLE
Symbols missing on AVR target

### ISSUE THREAD

**Issue by jonahbron** [rust-lang/compiler-builtins#318]
When compiling to the [avr-unknown-unknown](https://github.com/avr-rust/rust) platform using the compiler fork, I get errors about the following missing symbols.

* __ashlsi3
* __lshrsi3
* __divmodti4
* __ashrsi3

I'm trying to track down information on how to fix this.  Someone in the original ticket I opened suggested I fork compiler-builtins and implement these intrinsics.

https://github.com/avr-rust/rust/issues/149#issuecomment-537081518

I'd love any direction anyone can offer on whether this is really the correct approach, and how to add these, this is all super new to me.  Thanks in advance.

**Comment by alexcrichton** [comment]
Thanks for the report! These intrinsics haven't yet been ported to Rust yet, presumably because they haven't been needed by other targets. They can be added at any time though! You'll probably be editing `src/int/*.rs`, and there should be examples throughout there of how to write the intrinsics.

You'll need to consult gcc/clang though to see what the expected signature of these intrinsics are.

**Comment by jonahbron** [comment]
@alexcrichton I've tried adding missing symbols until the linker stopped complaining.

```diff
diff --git a/src/avr.rs b/src/avr.rs
new file mode 100644
index 0000000..8840940
--- /dev/null
+++ b/src/avr.rs
@@ -0,0 +1,25 @@
+use core::intrinsics;
+
+// #[cfg(target_arch = "avr")]
+// #[naked]
+// #[cfg_attr(not(feature = "mangled-names"), no_mangle)]
+// pub unsafe fn __ashlsi3() {
+//     asm!("andi r2, r2, 0x1f" ::: "memory" : "volatile");
+//     intrinsics::unreachable();
+// }
+
+// #[cfg(target_arch = "avr")]
+// #[naked]
+// #[cfg_attr(not(feature = "mangled-names"), no_mangle)]
+// pub unsafe fn __lshrsi3() {
+//     asm!("andi r2, r2, 0x1f" ::: "memory" : "volatile");
+//     intrinsics::unreachable();
+// }
+
+// #[cfg(target_arch = "avr")]
+// #[naked]
+// #[cfg_attr(not(feature = "mangled-names"), no_mangle)]
+// pub unsafe fn __ashrsi3() {
+//     asm!("andi r2, r2, 0x1f" ::: "memory" : "volatile");
+//     intrinsics::unreachable();
+// }
```

I tried to use this from libgcc as a reference:

https://github.com/gcc-mirror/gcc/blob/master/libgcc/config/lm32/_ashlsi3.S#L34
https://github.com/gcc-mirror/gcc/blob/master/libgcc/config/lm32/_lshrsi3.S#L31
https://github.com/gcc-mirror/gcc/blob/master/libgcc/config/lm32/_ashrsi3.S#L31

When I add these and configure `Xargo.toml` to point to it:

```toml
[dependencies.core]
stage = 0

[dependencies.compiler_builtins]
stage = 1
path = "../compiler-builtins/"
```

The code does compile (unlike before).  However the code that it's supposed to fix at run-time doesn't behave as expected.  Does it seem like I've implemented these functions incorrectly?

**Comment by jonahbron** [comment]
@alexcrichton I've run into some very interesting behavior.  As soon as I make compiler-builtins a dependency with Xargo, my program suddenly compiles.  This is odd, considering those missing symbols are not provided by compiler-builtins right now.  However, the area of my application affected by these errors does not behave as expected still, despite now compiling.

**Comment by alexcrichton** [comment]
Ah sorry I'm not entirely sure what's happening in that case, most things having to do with compiler-builtins tend to be very-specific bugs or difficult to reproduce.

**Comment by jonahbron** [comment]
@alexcrichton It seems like things are in fact working (bugs in my own code it seems).  I still have no idea why adding the compiler-builtins dependency magically fixes the problems when it doesn't have the symbols that the compiler is complaining about, but if it compiles I'm happy :man_shrugging:
