### ISSUE TITLE
CFI directives missing on __rust_probestack

### ISSUE THREAD

**Issue by tmandry** [rust-lang/compiler-builtins#325]
https://github.com/rust-lang/compiler-builtins/pull/306 added frame pointers so that backtraces would be available from failed stack probes. Unfortunately, this does not work in build configurations which use DWARF/CFI information for unwinding. (On Fuchsia we use this exclusively, but it's an option on other platforms as well.)

The way of enabling backtraces on these platforms is to use CFI directives, like https://github.com/rust-lang/compiler-builtins/pull/305 did. Unfortunately, that implementation was messier due to needing external assembly files. Still, it's the only way to get full backtrace information in DWARF.

**Comment by alexcrichton** [comment]
I'm not familiar with it myself, but if LLVM inline assembly has a way to support this that'd be the best way to go. If not, though, using assembly files for rust-lang/rust builds and having the inline-Rust used for other builds seems like a possible way to go to fix this

**Comment by tmandry** [comment]
It does seem possible to use LLVM inline assembly; see e.g. https://github.com/llvm-mirror/compiler-rt/blob/69445f095c22aac2388f939bedebf224a6efcdaf/lib/fuzzer/FuzzerUtilFuchsia.cpp#L176

**Comment by tmandry** [comment]
Fixed by https://github.com/rust-lang/compiler-builtins/pull/328.
