### ISSUE TITLE
build error rv32imc which does not have atomics at all

### ISSUE THREAD

**Issue by rminnich** [rust-lang/compiler-builtins#326]
Please see https://github.com/oreboot/oreboot/pull/189

 we are compiling to the lowrisc/ibex cpu used in the opentitan earlygrey soc. This is an r32imc, i.e. no atomics.

This is similar to the just-closed issue for rv64, which had no atomic load-store for u16.

error: linking with `rust-lld` failed: exit code: 1
  |
  = note: "rust-lld" "-flavor" "gnu" "-L" "/home/ryan/repos/oreboot/src/mainboard/opentitan/crb/target/sysroot/lib/rustlib/riscv32imc-unknown-none-elf/lib" "/home/ryan/repos/oreboot/src/mainboard/opentitan/crb/target/riscv32imc-unknown-none-elf/release/deps/crb-d971ec7d0b119a72.crb.ae8f5638-cgu.3.rcgu.o" "-o" "/home/ryan/repos/oreboot/src/mainboard/opentitan/crb/target/riscv32imc-unknown-none-elf/release/deps/crb-d971ec7d0b119a72" "--gc-sections" "-L" "/home/ryan/repos/oreboot/src/mainboard/opentitan/crb/target/riscv32imc-unknown-none-elf/release/deps" "-L" "/home/ryan/repos/oreboot/src/mainboard/opentitan/crb/target/release/deps" "-L" "/home/ryan/repos/oreboot/src/mainboard/opentitan/crb/target/sysroot/lib/rustlib/riscv32imc-unknown-none-elf/lib" "-Bstatic" "/home/ryan/repos/oreboot/src/mainboard/opentitan/crb/target/sysroot/lib/rustlib/riscv32imc-unknown-none-elf/lib/libcompiler_builtins-ddf3439031b17ea4.rlib" "-Tlink.ld" "-Bdynamic"

  = note: rust-lld: error: undefined symbol: __atomic_load_1
          >>> referenced by compiler_builtins.bsqadl41-cgu.7
          >>>               compiler_builtins-ddf3439031b17ea4.compiler_builtins.bsqadl41-cgu.7.rcgu.o:(__llvm_memcpy_element_unordered_atomic_1) in archive /home/ryan/repos/oreboot/src/mainboard/opentitan/crb/target/sysroot/lib/rustlib/riscv32imc-unknown-none-elf/lib/libcompiler_builtins-ddf3439031b17ea4.rlib
          >>> referenced by compiler_builtins.bsqadl41-cgu.7
          >>>               compiler_builtins-ddf3439031b17ea4.compiler_builtins.bsqadl41-cgu.7.rcgu.o:(__llvm_memmove_element_unordered_atomic_1) in archive /home/ryan/repos/oreboot/src/mainboard/opentitan/crb/target/sysroot/lib/rustlib/riscv32imc-unknown-none-elf/lib/libcompiler_builtins-ddf3439031b17ea4.rlib
          >>> referenced by compiler_builtins.bsqadl41-cgu.7
          >>>               compiler_builtins-ddf3439031b17ea4.compiler_builtins.bsqadl41-cgu.7.rcgu.o:(__llvm_memmove_element_unordered_atomic_1) in archive /home/ryan/repos/oreboot/src/mainboard/opentitan/crb/target/sysroot/lib/rustlib/riscv32imc-unknown-none-elf/lib/libcompiler_builtins-ddf3439031b17ea4.rlib

**Comment by alexcrichton** [comment]
Thanks for this! It should be fixed in 0.1.21 in theory, can you check what version you're using?

**Comment by rminnich** [comment]
rminnich@xcpu:~/projects/oreboot/oreboot/src/mainboard/opentitan/crb$ more .cargo/config 
[build]
target = "riscv32imc-unknown-none-elf"

[target.riscv32imc-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tlink.ld",
]
rminnich@xcpu:~/projects/oreboot/oreboot/src/mainboard/opentitan/crb$ rustc --version
rustc 1.41.0-nightly (82cf3a448 2019-11-14)

did we misconfigure something?

**Comment by alexcrichton** [comment]
Unfortunately that's not quite enough information to go on. Without more information about how to reproduce and knowing what version of this crate you're using I won't be able to help.

**Comment by rminnich** [comment]
it seems to be fixed anyway. You all fix bugs faster than I can write readable bug reports it seems :-)

**Comment by bjorn3** [comment]
Probably fixed in https://github.com/rust-lang/compiler-builtins/pull/324.
