### ISSUE TITLE
multiple rlib candidates for `compiler_builtins` found

### ISSUE THREAD

**Issue by tomaka** [rust-lang/compiler-builtins#334]
Sorry if this is not the right place to report this issue.

After upgrading to the latest nightly, my `no_std` project suddenly stopped compiling with this error:

```
error[E0465]: multiple rlib candidates for `compiler_builtins` found
  |
  = note: candidate #1: /home/pierre/Projets/os/target/arm-freestanding/release/deps/libcompiler_builtins-26c139968e75b8d8.rlib
  = note: candidate #2: /home/pierre/Projets/os/target/arm-freestanding/release/deps/libcompiler_builtins-1ff647597e07803f.rlib

error[E0463]: can't find crate for `compiler_builtins`
```

I'm following the instructions in `README.md` which ask you to add `compiler_builtins` as a dependency and add `extern crate compiler_builtins;`.

It seems that Rust indeed passes `compiler_builtins` twice when compiling the crate. Here's a fragment of the invocation of `rustc`:
```
--extern 'noprelude:compiler_builtins=/home/pierre/Projets/os/target/arm-freestanding/release/deps/libcompiler_builtins-1ff647597e07803f.rlib' --extern compiler_builtins=/home/pierre/Projets/os/target/arm-freestanding/release/deps/libcompiler_builtins-26c139968e75b8d8.rlib
```

Interestingly, if I do that in Cargo.toml:
```toml
compiler_builtins_under_a_different_name = { package = "compiler_builtins", git = "https://github.com/rust-lang/compiler-builtins" }
```
And then `extern crate compiler_builtins_under_a_different_name;`, then everything works fine on some platforms but gives linking errors ~~for `memcpy`~~ for `memcmp` on some others.

**Comment by bjorn3** [comment]
Are you using `-Zbuild-std`? In that case, you should not add `compiler_builtins` as dependency yourself. `cargo` will build it automatically for you.

**Comment by tomaka** [comment]
> Are you using -Zbuild-std? In that case, you should not add compiler_builtins as dependency yourself. cargo will build it automatically for you.

Yes I'm using `-Zbuild-std`! I'm doing `-Zbuild-std=core,compiler_builtins,alloc`

Not adding compiler_builtins as a dependency leads to `ld.lld: error: undefined symbol: memcmp`.

**Comment by bjorn3** [comment]
It seems that the `mem` feature of `compiler-builtins` is not enabled by default. By the way `compiler_builtins` is enabled by default when `core` is enabled: https://github.com/rust-lang/cargo/blob/86134e7666a088682f20b76278c3ee096a315218/src/cargo/core/compiler/standard_lib.rs#L25-L27

**Comment by tomaka** [comment]
Rust seems to use `compiler_builtins` version `0.1.16` (https://github.com/rust-lang/rust/blob/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9/src/libstd/Cargo.toml#L23), but this version defines language items that don't even exist anymore.

I'm extremely confused as to what to do next. I have no idea how `compiler_builtins` works even on a normal platform, and I have no idea why/how it worked before I updated my nightly version.

**Comment by bjorn3** [comment]
Rust actually pins `0.1.22` in `Cargo.lock`: https://github.com/rust-lang/rust/blob/f6dca76be55dd6bb8d0d7d3b6bc39ae8373db506/Cargo.lock#L571-L573. I wonder if `-Zbuild-std` uses `Cargo.lock`. If so, you may be able to edit it to use `compiler-builtins 0.1.22`.

**Comment by tomaka** [comment]
(sorry, I deleted a comment in-between, as I realized what you said)

I think my issue is https://github.com/rust-lang/wg-cargo-std-aware/issues/15

**Comment by alexcrichton** [comment]
I think this is likely a bug with `-Zbuild-std` rather than this crate itself, so mind reopening this on the std-aware repository?

**Comment by tomaka** [comment]
Reopened as https://github.com/rust-lang/wg-cargo-std-aware/issues/53

**Comment by AthiraRamakrishna** [comment]
Hi 

is there a solution for this already? I face a similar issue when building for a custom target with -Zbuild-std=core,alloc and providing compiler_builtins as dependency in Cargo.toml file. 

Any help much appreciated. Thanks

**Comment by tgross35** [comment]
@AthiraRamakrishna this has been closed for a long time. Could you open a new issue describing what you are trying and what problem you are experiencing?
