### ISSUE TITLE
riscv32imac-unknown-none-elf: missing __atomic_fetch_add_4

### ISSUE THREAD

**Issue by xobs** [rust-lang/compiler-builtins#346]
The target `riscv32imac-unknown-none-elf` supports atomic instructions, which is what the "-a-" signifies in "riscv32imac".  It is possible to instantiate `core::sync::atomic::AtomicUsize` in Rust.

However, this requires the symbol `__atomic_fetch_add_4`, which is not available:

```
  = note: rust-lld: error: undefined symbol: __atomic_fetch_add_4
          >>> referenced by atomic.rs:0 (/rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/sync\atomic.rs:0)             >>>               lto.tmp:(core::sync::atomic::atomic_add::h40ce36395a1e4653)

          rust-lld: error: undefined symbol: __atomic_fetch_sub_4
          >>> referenced by atomic.rs:0 (/rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/sync\atomic.rs:0)             >>>               lto.tmp:(core::sync::atomic::atomic_sub::hb4a663ea9a75ea76)
```

This could be mocked in an external asm file, however it seems like this should be a compiler builtin, and therefore should be part of this crate.

**Comment by alexcrichton** [comment]
This likely indicates that the LLVM target is misconfigured. This typically means that atomics aren't being lowered to instructions because they're being lowered to intrinsic calls. It would probably be good to double check the target specification for this target and ensure that the requisite way to enable atomics for the riscv platform is turned on. I don't know what this way is myself, unfortunately, but I'm sure it exists in LLVM!

**Comment by xobs** [comment]
Thanks for the tip.  I'll look into modifying the Rust target definition, and post a patch to the compiler if I find something.  I'll update this bug with my findings.

**Comment by xobs** [comment]
It seems like the problem only appears when I set `linker-plugin-lto`.  To reproduce:

```rust
#![no_std]
#![no_main]

use core::sync::atomic::{AtomicUsize, Ordering};
static MM_HANDLE_COUNT: AtomicUsize = AtomicUsize::new(0);

#[no_mangle]
pub extern "C" fn _start() -> ! {
    let _count = MM_HANDLE_COUNT.fetch_add(1, Ordering::SeqCst);// unsafe { MM_HANDLE_COUNT += 1; MM_HANDLE_COUNT - 1 };
    loop {}
}

use core::panic::PanicInfo;
#[panic_handler]
fn handle_panic(_arg: &PanicInfo) -> ! {
    loop {}
}

#[no_mangle]
pub extern "C" fn abort() -> ! {
    loop {}
}
```

Build with:

```sh
$  rustc -C linker-plugin-lto main.rs --target riscv32imac-unknown-none-elf
error: linking with `rust-lld` failed: exit code: 1
  |
  = note: "rust-lld" "-flavor" "gnu" "-plugin-opt=O0" "-plugin-opt=mcpu=generic-rv32" "-L" "C:\\Users\\smcro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\riscv32imac-unknown-none-elf\\lib" "main.main.7rcbfp3g-cgu.0.rcgu.o" "main.main.7rcbfp3g-cgu.1.rcgu.o" "main.main.7rcbfp3g-cgu.2.rcgu.o" "-o" "main" "--gc-sections" "-L" "C:\\Users\\smcro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\riscv32imac-unknown-none-elf\\lib" "-Bstatic" "C:\\Users\\smcro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\riscv32imac-unknown-none-elf\\lib\\librustc_std_workspace_core-412853335266c038.rlib" "C:\\Users\\smcro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\riscv32imac-unknown-none-elf\\lib\\libcore-892f07abb10545bd.rlib" "C:\\Users\\smcro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\riscv32imac-unknown-none-elf\\lib\\libcompiler_builtins-343449e7a3140935.rlib" "-Bdynamic"
  = note: rust-lld: error: undefined symbol: __atomic_fetch_add_4
          >>> referenced by main.7rcbfp3g-cgu.2
          >>>               lto.tmp:(core::sync::atomic::AtomicUsize::fetch_add::h51d5839ade8a654d)


error: aborting due to previous error
$
```

Where is the appropriate place to report this?

**Comment by alexcrichton** [comment]
Ah yes that'd do it! LLD is the one doing codegen here and that's not configured the same way as rustc. This may be a bug in how rustc is invoking the linker, it may be a bug in the LLVM module since it doesn't say atomics are enabled, honestly I'm not entirely sure. I know very little about LTO code generation and how the compiler options make their way to the linker, so I don't know where this should be reported.

**Comment by bjorn3** [comment]
> "-plugin-opt=mcpu=generic-rv32"

That is a different target cpu than `riscv32imac`, right?

**Comment by xobs** [comment]
The only cpu options appear to be `generic-rv32` and `generic-rv64`, possibly with the additions of `rocket-rv32` and `rocket-rv64` (that don't appear to work as a target cpu).

You may be on to something, however, because the `features` section of the target definition is `  "features": "+m,+a,+c",`, and that doesn't appear to be getting passed to `rust-lld`.

**Comment by xobs** [comment]
Furthermore, I can elicit this response by passing `-plugin-opt=mcpu=help`:

```
Available CPUs for this target:

  generic-rv32 - Select the generic-rv32 processor.
  generic-rv64 - Select the generic-rv64 processor.

Available features for this target:

  64bit - Implements RV64.
  a     - 'A' (Atomic Instructions).
  c     - 'C' (Compressed Instructions).
  d     - 'D' (Double-Precision Floating-Point).
  e     - Implements RV32E (provides 16 rather than 32 GPRs).
  f     - 'F' (Single-Precision Floating-Point).
  m     - 'M' (Integer Multiplication and Division).
  relax - Enable Linker relaxation..

Use +feature to enable a feature, or -feature to disable it.
For example, llc -mcpu=mycpu -mattr=+feature1,-feature2
rust-lld: error: undefined symbol: __atomic_fetch_add_4
>>> referenced by test.7rcbfp3g-cgu.1
>>>               lto.tmp:(core::sync::atomic::AtomicUsize::fetch_add::hf69f49ebe725a0f1)
```

However, that message appears to be misleading since the `mattr` argument doesn't actually work:

```
$ [...]/rust-lld.exe -flavor gnu "-plugin-opt=O0" "-plugin-opt=mcpu=generic-rv32" "-plugin-opt=mattr=+a" [...]
rust-lld: error: --plugin-opt: rust-lld.exe: Unknown command line argument 'mattr=+a'.  Try: 'C:\Users\smcro\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\bin\rust-lld.exe --help'
```

**Comment by xobs** [comment]
Oh.  The syntax appears to be ` "-plugin-opt=--mattr=+a"`.  I'll move this over to the rust bug, because I can work on a fix now.
