### ISSUE TITLE
bcmp missing

### ISSUE THREAD

**Issue by repmop** [rust-lang/compiler-builtins#352]
LLVM emits bcmp for `#![no_builtins]`, `#![no_std]` enabled crates on rustc 1.43.0 while targeting i686-unknown-linux-musl.

This was supposedly resolved in #303, but still appears to be a problem.

Specifically, the memcmp [here](https://github.com/rust-lang/rust/blob/93eed402adbe9e7a532995500d50716d52eefee9/src/libcore/slice/mod.rs#L5867) is being converted to a bcmp.

**Comment by josephlr** [comment]
This doesn't seem like a bug, emitting `bcmp` instead of `memcmp` on musl seems fine.

What's worked for me is either:
  - Using musl's libc which has `bcmp`
  - Using this crate with the `mem` feature enabled (which is done by default with `cargo-xbuild`)

**Comment by Amanieu** [comment]
compiler-builtins provides an implementation of bcmp so this should work fine.
