### ISSUE TITLE
ARM Thumb targets need fmax*/fmin* intrinsics

### ISSUE THREAD

**Issue by saleemrashid** [rust-lang/compiler-builtins#354]
`core::f32` and `core::f64` expose `max` and `min`, but these use the `fmax*`/`fmin*` intrinsics, which aren't exposed for the Thumb targets https://github.com/rust-lang/compiler-builtins/blob/cde22bc180391e75de1c189fe29f442ada86ccde/src/math.rs#L92-L99

https://rust.godbolt.org/z/B4tB6w

```rust
#![no_std]

pub fn maxf(a: f32, b: f32) -> f32 {
    a.max(b)
}

pub fn minf(a: f32, b: f32) -> f32 {
    a.min(b)
}

pub fn max(a: f64, b: f64) -> f64 {
    a.max(b)
}

pub fn min(a: f64, b: f64) -> f64 {
    a.min(b)
}
```

```asm
example::maxf:
        b       fmaxf

example::minf:
        b       fminf

example::max:
        b       fmax

example::min:
        b       fmin
```

**Comment by jordens** [comment]
https://paste.debian.net/1168430/
