### ISSUE TITLE
Safety of intrinsics

### ISSUE THREAD

**Issue by fpoli** [rust-lang/compiler-builtins#355]
Shouldn't `mem::__llvm_memcpy_element_unordered_atomic_1` and similar functions be marked as `unsafe`? The following program crashes with "Segmentation fault (core dumped)".

```rust
// compiler_builtins = "=0.1.23"

extern crate compiler_builtins;

fn main() {
    compiler_builtins::mem::__llvm_memcpy_element_unordered_atomic_1(
        std::ptr::null::<u128>() as *mut u8,
        std::ptr::null(),
        1
    );
}
```

**Comment by alexcrichton** [comment]
Ah yeah this should be unsafe for sure, thanks for the report!

**Comment by LukasKalbertodt** [comment]
What exactly does "similar function" mean? This seems like we should fix it sooner rather than later, but I unfortunately don't really know enough about this stuff to properly judge what should be `unsafe` and what not. I would guess that everything in `mem` should be `unsafe`, right?

**Comment by alexcrichton** [comment]
I'd interpret it the same as Rust, where safe means "impossible to cause UB regardless of arguments".

These take a raw pointer and that's unsafe since you can manufacture pointers.
