### ISSUE TITLE
Cannot cross-compile from x86_64 to i686 with LLVM 8

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/compiler-builtins#356]
As @eddyb found out, https://github.com/rust-lang/compiler-builtins/pull/311 introduced a [regression on old versions of LLVM](https://github.com/rust-lang/compiler-builtins/pull/311#issuecomment-612270089): cross-compilation to `i686-unknown-linux-gnu` on an x86_64 host is broken. In particular this currently prevents us from [ensuring 32bit tests work on PR CI](https://github.com/rust-lang/rust/pull/72053).

**Comment by RalfJung** [comment]
One option might be to simply revert that PR, since (from what I can see in https://github.com/rust-lang/rust/issues/58599) the unordered intrinsics are not actually used. But then I wonder why they lead to problems.

**Comment by Mark-Simulacrum** [comment]
It seems like at least gating them on LLVM >= 9 or whatever would be reasonable...

**Comment by RalfJung** [comment]
Does compiler-builtins have infrastructure for LLVM version gating?

**Comment by Amanieu** [comment]
Rust no longer supports LLVM 8.
