### ISSUE TITLE
`#[aapcs_on_arm]` is applied to two functions with no floating point

### ISSUE THREAD

**Issue by AaronKutch** [rust-lang/compiler-builtins#373]
In PR #332 and in my upcoming PR for fixing issue #367, I have noticed two functions, `__multi3` and `__divmoddi4`, which have `#[aapcs_on_arm]` for no apparent reason. Amanieu said that all it does is force soft-float convention even on hard-float targets. I checked the arm part of `compiler-rt` and don't see anything unusual with those functions. Those two functions are the only non-floating-point related functions with `#[aapcs_on_arm]` on them. Can I remove those two instances of `#[aapcs_on_arm]` in my two PRs?

**Comment by alexcrichton** [comment]
These are likely a mistake. IIRC we copied this mostly from compiler-rt, but even there it may have been a mistake or we mistakenly copied something over. Should be fine to fix!

**Comment by AaronKutch** [comment]
Ok just double checking, I will close this issue once both are fixed
