### ISSUE TITLE
Help, I am trying to port relibc to windows, and face the __chkstk issue

### ISSUE THREAD

**Issue by lygstate** [rust-lang/compiler-builtins#383]
C:\work\study\languages\rust\relibc>cl /MD kernel32.lib bufferoverflowu.lib target\debug\relibc.lib examples\test.c -X -Iinclude -Itarget\include -link  -NODEFAULTLIB
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.27.29111 版
版权所有(C) Microsoft Corporation。保留所有权利。

test.c
Microsoft (R) Incremental Linker Version 14.27.29111.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test.exe
-NODEFAULTLIB
kernel32.lib
bufferoverflowu.lib
target\debug\relibc.lib
test.obj
relibc.lib(compiler_builtins-88a1b2fb6f0103b9.compiler_builtins.7aumvbvw-cgu.10.rcgu.o) : error LNK2005: __udivti3 已经在 relibc.lib(compiler_builtins-39d38ac12950f0ad.compiler_builtins.7s4tkjsi-cgu.101.rcgu.o) 中定义
relibc.lib(compiler_builtins-88a1b2fb6f0103b9.compiler_builtins.7aumvbvw-cgu.10.rcgu.o) : error LNK2005: __umodti3 已经在 relibc.lib(compiler_builtins-39d38ac12950f0ad.compiler_builtins.7s4tkjsi-cgu.91.rcgu.o) 中定义
relibc.lib(compiler_builtins-88a1b2fb6f0103b9.compiler_builtins.7aumvbvw-cgu.12.rcgu.o) : error LNK2005: __muloti4 已经在 relibc.lib(compiler_builtins-39d38ac12950f0ad.compiler_builtins.7s4tkjsi-cgu.55.rcgu.o) 中定义
relibc.lib(relibc-9d9c08d1b0a05e35.4hpfjzg8pdsfqzra.rcgu.o) : error LNK2019: 无法解析的外部符号 pthread_init，函数 _ZN6relibc5start10init_array17ha673ba50bf14f52fE 中引用了该符号
relibc.lib(relibc-9d9c08d1b0a05e35.4hpfjzg8pdsfqzra.rcgu.o) : error LNK2019: 无法解析的外部符号 __preinit_array_start，函数 relibc_start 中引用了该符号
relibc.lib(relibc-9d9c08d1b0a05e35.4hpfjzg8pdsfqzra.rcgu.o) : error LNK2019: 无法解析的外部符号 __preinit_array_end，函数 relibc_start 中引用了该符号
relibc.lib(relibc-9d9c08d1b0a05e35.4hpfjzg8pdsfqzra.rcgu.o) : error LNK2019: 无法解析的外部符号 _init，函数 relibc_start 中引用了该符号
relibc.lib(relibc-9d9c08d1b0a05e35.4hpfjzg8pdsfqzra.rcgu.o) : error LNK2019: 无法解析的外部符号 __init_array_start，函数 relibc_start 中引用了该符号
relibc.lib(relibc-9d9c08d1b0a05e35.4hpfjzg8pdsfqzra.rcgu.o) : error LNK2019: 无法解析的外部符号 __init_array_end，函数 relibc_start 中引用了该符号
relibc.lib(relibc-9d9c08d1b0a05e35.4f7bjoz4nyl9872d.rcgu.o) : error LNK2001: 无法解析的外部符号 _tls_index
relibc.lib(relibc-9d9c08d1b0a05e35.2wmih4feibvw9owg.rcgu.o) : error LNK2001: 无法解析的外部符号 _tls_index
relibc.lib(relibc-9d9c08d1b0a05e35.1x5l4jupgiuvbkpn.rcgu.o) : error LNK2001: 无法解析的外部符号 _tls_index
relibc.lib(relibc-9d9c08d1b0a05e35.4nuobiwtkb3zdwi.rcgu.o) : error LNK2001: 无法解析的外部符号 _tls_index
relibc.lib(relibc-9d9c08d1b0a05e35.52c5u33q78mlilk9.rcgu.o) : error LNK2001: 无法解析的外部符号 _tls_index
relibc.lib(relibc-9d9c08d1b0a05e35.1x8g2g4krrmlz5q3.rcgu.o) : error LNK2001: 无法解析的外部符号 _tls_index
relibc.lib(relibc-9d9c08d1b0a05e35.4syvupwgp4u7bbps.rcgu.o) : error LNK2001: 无法解析的外部符号 _tls_index
relibc.lib(relibc-9d9c08d1b0a05e35.vixotrs3z2efb03.rcgu.o) : error LNK2001: 无法解析的外部符号 _tls_index
relibc.lib(relibc-9d9c08d1b0a05e35.32hfqahjeuk49qyz.rcgu.o) : error LNK2001: 无法解析的外部符号 _tls_index
relibc.lib(relibc-9d9c08d1b0a05e35.206xjy6h5e8hs1h.rcgu.o) : error LNK2001: 无法解析的外部符号 _tls_index
relibc.lib(relibc-9d9c08d1b0a05e35.zz2dtjlpmanf1h.rcgu.o) : error LNK2001: 无法解析的外部符号 _tls_index
relibc.lib(relibc-9d9c08d1b0a05e35.3gkoli02u3xvwi6l.rcgu.o) : error LNK2001: 无法解析的外部符号 _tls_index
relibc.lib(relibc-9d9c08d1b0a05e35.2h61x08khw1ukwbx.rcgu.o) : error LNK2001: 无法解析的外部符号 _tls_index
relibc.lib(relibc-9d9c08d1b0a05e35.3dwdb5p8xjdh2ne1.rcgu.o) : error LNK2001: 无法解析的外部符号 _tls_index
relibc.lib(relibc-9d9c08d1b0a05e35.434wb6pmguwct0qa.rcgu.o) : error LNK2001: 无法解析的外部符号 _tls_index
relibc.lib(relibc-9d9c08d1b0a05e35.2b4gng32pwix0ldd.rcgu.o) : error LNK2001: 无法解析的外部符号 _tls_index
relibc.lib(relibc-9d9c08d1b0a05e35.2wrawszkxk9rt8rm.rcgu.o) : error LNK2001: 无法解析的外部符号 _tls_index
relibc.lib(relibc-9d9c08d1b0a05e35.434wb6pmguwct0qa.rcgu.o) : error LNK2019: 无法解析的外部符号 __fini_array_end，函数 exit 中引用了该符号
relibc.lib(relibc-9d9c08d1b0a05e35.434wb6pmguwct0qa.rcgu.o) : error LNK2019: 无法解析的外部符号 __fini_array_start，函数 exit 中引用了该符号
relibc.lib(relibc-9d9c08d1b0a05e35.434wb6pmguwct0qa.rcgu.o) : error LNK2019: 无法解析的外部符号 _fini，函数 exit 中引用了该符号
relibc.lib(relibc-9d9c08d1b0a05e35.434wb6pmguwct0qa.rcgu.o) : error LNK2019: 无法解析的外部符号 pthread_terminate，函数 exit 中引用了该符号
relibc.lib(relibc-9d9c08d1b0a05e35.4ifofswltr4zyltf.rcgu.o) : error LNK2001: 无法解析的外部符号 __chkstk
relibc.lib(rand-6a35eaeaab7f31be.rand.a1ul4dd6-cgu.4.rcgu.o) : error LNK2001: 无法解析的外部符号 __chkstk
relibc.lib(relibc-9d9c08d1b0a05e35.1x5l4jupgiuvbkpn.rcgu.o) : error LNK2001: 无法解析的外部符号 __chkstk
relibc.lib(rand-6a35eaeaab7f31be.rand.a1ul4dd6-cgu.5.rcgu.o) : error LNK2001: 无法解析的外部符号 __chkstk
relibc.lib(rand-6a35eaeaab7f31be.rand.a1ul4dd6-cgu.7.rcgu.o) : error LNK2001: 无法解析的外部符号 __chkstk
relibc.lib(relibc-9d9c08d1b0a05e35.vpu42b44v1qtr6s.rcgu.o) : error LNK2001: 无法解析的外部符号 __chkstk
relibc.lib(posix_regex-a35eeca5f6847290.9sburftcvegype3.rcgu.o) : error LNK2001: 无法解析的外部符号 __chkstk
relibc.lib(goblin-fca5be98fc157ea8.goblin.2sopokfe-cgu.8.rcgu.o) : error LNK2001: 无法解析的外部符号 __chkstk
relibc.lib(rand-6a35eaeaab7f31be.rand.a1ul4dd6-cgu.0.rcgu.o) : error LNK2001: 无法解析的外部符号 __chkstk
relibc.lib(relibc-9d9c08d1b0a05e35.zz2dtjlpmanf1h.rcgu.o) : error LNK2001: 无法解析的外部符号 __chkstk
relibc.lib(relibc-9d9c08d1b0a05e35.3gkoli02u3xvwi6l.rcgu.o) : error LNK2001: 无法解析的外部符号 __chkstk
relibc.lib(rand-6a35eaeaab7f31be.rand.a1ul4dd6-cgu.13.rcgu.o) : error LNK2001: 无法解析的外部符号 __chkstk
relibc.lib(relibc-9d9c08d1b0a05e35.1kzz6vo5r9kpp7wu.rcgu.o) : error LNK2001: 无法解析的外部符号 __chkstk
relibc.lib(dlmalloc.o) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck
relibc.lib(relibc-9d9c08d1b0a05e35.phoxdfwpp2w85bj.rcgu.o) : error LNK2019: 无法解析的外部符号 __restore_rt，函数 _ZN6relibc6header6signal9sigaction28_$u7b$$u7b$closure$u7d$$u7d$17hc01bd509a69f5b63E 中引用了该符号
relibc.lib(relibc-9d9c08d1b0a05e35.52c5u33q78mlilk9.rcgu.o) : error LNK2001: 无法解析的外部符号 __restore_rt
test.exe : fatal error LNK1120: 14 个无法解析的外部命令

**Comment by bjorn3** [comment]
Can you please post an english version of the error message? Most people outside China van't read chinese.

**Comment by tgross35** [comment]
This has been open for a long time with no followup so I am going to close it. Please reopen if there are updates.
