### ISSUE TITLE
Can `testcrate/build.rs` and some other redundant things be deleted?

### ISSUE THREAD

**Issue by AaronKutch** [rust-lang/compiler-builtins#395]
After PR #384 was merged, I thought I would look around and try to close as many easy issues as I could while my brain is still familiar with `compiler-builtins`. I realized that issues #162 and #168 was caused by the fact that fixing the exponent would enable the generation of subnormal numbers, and the soft multiplication does not support subnormal numbers (at least not yet). I haven't messed with `build.rs` much because I thought it was doing some really special testing. After looking it over, I realize all it is is a hackier version of the tests now under `tests/`. It doesn't go anywhere near the level of rigorousness my new tests achieve (it hasn't found any of the subnormal or rounding edge cases #384 found).

The only thing `build.rs` has that the new testing suite doesn't is a few more tests related to the special intrinsics that ARM gets. Should I open a PR to test the remaining functions and delete `build.rs` and `tests/generated.rs` altogether? Also, I think the references to `panic-handler` and `utest_macros` crates can be deleted. Some documentation says they were introduced as a workaround for https://github.com/rust-lang/rust/issues/51647, but that issue was closed a long time ago.

**Comment by alexcrichton** [comment]
I think as long as we test basically the same amount of things it's fine to refactor/clean up as necessary personally. I forget the exact intricacies of how this is all tested, but I see no reason to keep one specific way of testing over another!

**Comment by AaronKutch** [comment]
fixed by #397
