### ISSUE TITLE
Using crate on no_std windows causes undefined symbols to be referenced on x86

### ISSUE THREAD

**Issue by wumb0** [rust-lang/compiler-builtins#403]
I am using this crate for the mem built-ins so I don't have to define them manually in a no_std crate. This is for msvc toolchains, not gnu. However, the int and float modules are also included. This is fine on x86_64, but on x86 functions/symbols to do 64-bit integer math and float math are included but are unresolved. These symbols include:
- __aulldiv
- __alldiv
- __aullrem
- __aullrem
- __fltused

It would be nice to have a feature (or features) to not include these types when all I need are the mem functions. Currently there is no way to exclude them other than cloning and modifying the crate directly or defining them in my crate as no-ops. For my use case that's fine, but I thought I'd just report it in case anyone else runs into this. 

I can submit a PR adding a no-int and no-float feature if that would help. Though, I do realize the appeal of not adding too many feature flags (this is now the 2nd and 3rd addition I am suggesting between two issues). 

Thanks!

**Comment by Amanieu** [comment]
Windows programs should always link to `ntdll.dll`, which is where these symbols come from. In fact it is impossible not to have `ntdll.dll` in a windows process because that is the very first thing loaded by the kernel into the process address space.

The proper solution here is to ensure you are linking with `ntdll.dll` (double-check your linker options?).

**Comment by wumb0** [comment]
It's worth noting that my specific use-case here was in a situation where I was trying to eliminate all external references. 
I'll concede the fact that my use case is outside the scope of responsibility of the compiler-builtins crate so I think this can just be closed.
