### ISSUE TITLE
duplicated git tags 0.1.56 and 0.1.65 created

### ISSUE THREAD

**Issue by klensy** [rust-lang/compiler-builtins#447]
https://github.com/rust-lang/compiler-builtins/releases/tag/0.1.56
https://github.com/rust-lang/compiler-builtins/releases/tag/0.1.65

Second one is typo, obviously.

**Comment by Amanieu** [comment]
Sadly the second one is the one that actually got published to crates.io. I figured it doesn't hurt to just skip 10 minor versions.
