### ISSUE TITLE
Please make aeabi division functions use weak linkage, because they are incorrect for ARMv4T

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/compiler-builtins#477]
The division functions included in this crate pop the link-register value directly into `pc` to return. This is correct for interworking code with v5T and later, but it is **incorrect** for v4T.

With v4T, you *must* use `bx` to switch code modes.

At this time I'm not aware of a way to `cfg` on the ARM version of a target. I think the best fix is to just declare the functions as weak linkage, and then v4T users can just override the functions on their end.

**Comment by Amanieu** [comment]
You can use `cfg(target_feature = "v5te")` for this.

**Comment by Lokathor** [comment]
Hmm. Interesting!

Would you also be willing to accept a PR for weak linkage on the division functions anyway? Because even if I use that target_feature to fix up these general functions with the correct return instructions (which I'll try to do later today) I would also like to be able to define my own versions that are stored in RAM rather than ROM because of the speed difference (it's like a 5x time difference in my case).

**Comment by Amanieu** [comment]
I think that we should have weak linkage on all functions in compiler-builtins actually, subject to target support. Anything except apple/windows uses ELF where this should work fine.
