### ISSUE TITLE
wrong define of 128-bit related functions like `__multi3` and `__floatuntidf` on `csky`

### ISSUE THREAD

**Issue by Dirreke** [rust-lang/compiler-builtins#551]
I have added `csky-unknown-linux-gnuabiv2` and `csky-unknown-linux-gnuabiv2hf` last days in https://github.com/rust-lang/rust/pull/113658 . And I got `SIGSEGV` when I run a executable file on csky.

I checked the file and found that in `LLVM-IR` file of `compiler-buildins`, (Taking `__floatuntidf` as an example),it defines `__floatuntidf`  as 
```
define hidden noundef double @__floatuntidf(ptr noalias nocapture noundef readonly align 4 dereferenceable(16) %i) unnamed addr 
```
which has a `ptr` parameter but not values.

In executable files, the value of parameters are passed to the `__floatuntidf`. and then it regard the value as an address to load data, which causes the `SIGSEGV`

---

It's confused me that what caused the parameters become `ptr`. 
Is this function compiled from [float/conv.rs](https://github.com/rust-lang/compiler-builtins/blob/d1d785a538d51d0082c3e6209a28c9fb1a90ec3c/src/float/conv.rs#L99C1-L104) or anywhere else?
And how can I fixed it?

**Comment by bjorn3** [comment]
What is the ABI for this function supposed to be? i128 can't be passed in a single register, so is it split into two registers or is it handled in a different way? And is this handling consistent with the way it is passed for regular functions or will it need a similar hack to `#[unadjusted_on_win64]` in the `intrinsics!` macro?

**Comment by Dirreke** [comment]
in the other platform like arm, it's defined as
```
define hidden double @_ZN17compiler_builtins5float4conv13__floatuntidf17h61afb9c475eb7bc7E(i128 %i) unnamed_addr #1
```
i128 will be divided to 4 i32 and passed to the `__floatuntidf`.

Passing the value to functions but not address is consitent with the funciton define in [float/conv.rs](https://github.com/rust-lang/compiler-builtins/blob/d1d785a538d51d0082c3e6209a28c9fb1a90ec3c/src/float/conv.rs#L99C1-L104)

**Comment by bjorn3** [comment]
> Passing the value to functions but not address is consitent with the funciton define in [float/conv.rs](https://github.com/rust-lang/compiler-builtins/blob/d1d785a538d51d0082c3e6209a28c9fb1a90ec3c/src/float/conv.rs#L99C1-L104)

The CSky C ABI definition rustc specifies that every type larger than 64bit and every aggregate type is to be passed as by-ref: https://github.com/rust-lang/rust/blob/271dcc1d40b57ad129d88fef1aa7f239308fbfb4/compiler/rustc_target/src/abi/call/csky.rs#L13-L14 Based on reading the ABI docs it is incorrect for both 128bit ints and aggregate types. These are to be passed in registers where possible and spilling onto the stack when there are not enough argument registers. And for returning it uses registers where possible and a return value pointer when larger than 64bit. You need to reproduce the entire ABI handling logic of clang at https://github.com/llvm/llvm-project/blob/4a074f32a6914f2a8d7215d78758c24942dddc3d/clang/lib/CodeGen/Targets/CSKY.cpp#L76-L162 in rustc.

**Comment by Dirreke** [comment]
Thanks! I will close it and make a PR in rust in a few days
