### ISSUE TITLE
The `USE_NATIVE_FULL_ITERATIONS` codepath in `div64` is broken

### ISSUE THREAD

**Issue by koute** [rust-lang/compiler-builtins#555]
It looks like [this codepath](https://github.com/rust-lang/compiler-builtins/blob/fdc1a87f471141de366045a212386af0cd83d44d/src/float/div.rs#L764) is completely broken. If enabled like this:

```diff
diff --git a/src/float/div.rs b/src/float/div.rs
index 8c4cf55..d15c2b9 100644
--- a/src/float/div.rs
+++ b/src/float/div.rs
@@ -466,7 +466,7 @@ where
 {
     const NUMBER_OF_HALF_ITERATIONS: usize = 3;
     const NUMBER_OF_FULL_ITERATIONS: usize = 1;
-    const USE_NATIVE_FULL_ITERATIONS: bool = false;
+    const USE_NATIVE_FULL_ITERATIONS: bool = true;
 
     let one = F::Int::ONE;
     let zero = F::Int::ZERO;
@@ -922,3 +922,8 @@ intrinsics! {
         a / b
     }
 }
+
+#[test]
+fn test_div64() {
+    div64(10.0_f64, 5.0_f64);
+}

```

 it fails with an overflow:

```
thread 'float::div::test_div64' panicked at 'attempt to multiply with overflow', src/float/div.rs:767:17
```

Looking at this code and looking at the `div32` implementation I'm guessing this is how it should be fixed?

```diff
diff --git a/src/float/div.rs b/src/float/div.rs
index 8c4cf55..4ea7500 100644
--- a/src/float/div.rs
+++ b/src/float/div.rs
@@ -764,8 +764,8 @@ where
     let mut x_uq0 = if USE_NATIVE_FULL_ITERATIONS {
         for _ in 0..NUMBER_OF_FULL_ITERATIONS {
             let corr_uq1: u64 = 0.wrapping_sub(
-                (CastInto::<u64>::cast(x_uq0) * (CastInto::<u64>::cast(b_uq1))) >> F::BITS,
-            );
+                (CastInto::<u64>::cast(x_uq0) as u128 * (CastInto::<u64>::cast(b_uq1) as u128)) >> F::BITS,
+            ) as u64;
             x_uq0 = ((((CastInto::<u64>::cast(x_uq0) as u128) * (corr_uq1 as u128))
                 >> (F::BITS - 1)) as u64)
                 .cast();
```

**Comment by tgross35** [comment]
Yeah, the float division implementation is pretty fragile. The proposed fix would make `f32` also use `u128` math, which is better to avoid when not necessary.

Do you have a usecase where you want to tweak this? I am refactoring this as part of https://github.com/rust-lang/compiler-builtins/pull/622, but don'tr really plan to expose this configuration (instead it will use full iterations only if `2xBITS` is <= pointer width, so it will start avoiding 64-bit math on <=32-bit platforms).

**Comment by koute** [comment]
> Do you have a usecase where you want to tweak this?

I don't. I just found this bug because I essentially forked this code to run in a `const fn` as a soft float. (So my only usecase here would be "I wish all of these functions were `const fn`".)

**Comment by tgross35** [comment]
Oh, that is an interesting idea. In theory all of these should be usable for expansion at comptime, but the use of traits probably makes it pretty hard to use directly in actual `const` functions. The compiler uses [`rustc_apfloat`](https://github.com/rust-lang/rustc_apfloat) for its comptime math, but it is also generic.

`const` float math has been proposed for stabilization, so maybe you won't need this at all soon https://github.com/rust-lang/rust/pull/128596.

**Comment by tgross35** [comment]
The implementation changed recently, selecting the iteration count is done at https://github.com/rust-lang/compiler-builtins/blob/bb18ce58c2b5fec081a5dd3553aa960a36b8de5c/src/float/div.rs#L507-L529. Based on my testing, this should work with both half and full iterations; but even if things aren't perfect, I don't think this issue has any specific action item for this issue.
