### ISSUE TITLE
Adding feature to port `libm` for any target

### ISSUE THREAD

**Issue by Amjad50** [rust-lang/compiler-builtins#576]
Hello.

I have been working with creating a new target for some platform, and working on `std`.
This target doesn't have libc, so it doesn't have the math symbols.

I was wondering if we could have a feature that will implement the math symbols from `libm` as it does now for targets that have `os = none` (and other targets).

I'm having a lot of trouble getting `libm` linking somehow to `std`, as I can't just add it as a dependency for that target.

Let me know what you think, and if there is any issues I don't know about.

Thanks

**Comment by Nilstrieb** [comment]
Take a look at the libm crate.

**Comment by Amjad50** [comment]
The issue is functions used in the standard library, like '%' in f32. If you used this operator, what is being called is 'fmod'. libm has this function implemented in rust but since it's not exported as a C function, the linker can't find it

**Comment by Amjad50** [comment]
I found a way to make libm compilable from 'std', I think it's a better approach.

I'll close this
