### ISSUE TITLE
aarch64 windows build failure

### ISSUE THREAD

**Issue by theKidOfArcrania** [rust-lang/compiler-builtins#604]
There is a bug when trying to build for windows arm64 target. See in [line 145](https://github.com/rust-lang/compiler-builtins/blob/a991664446c5d766b58e7f45a589831e8c3abf6e/build.rs#L145) concatenates a path of env `$OUT_DIR` to `"/outlined_atomics.rs"`. The problem arises in windows because `$OUT_DIR` may resolve to an unc path in windows, and those do not support having forward slashes. Using something like `Path.join(...)` should fix this bug.

**Comment by Amanieu** [comment]
I don't have a setup for building arm64 windows. Could you submit a PR with the fix once you have tested it?
