### ISSUE TITLE
Operations not available on ARMv6-M targets

### ISSUE THREAD

**Issue by japaric** [rust-lang/compiler-builtins#75]
These operations are not available on the `thumbv6m-none-eabi` target:
- `f64 as i64`
- `f64 as u64`
- `f64 == f64`
- `f64 > f64`
- `f64 < f64`
- `f32 as i64`
- `f32 as u64`
- `f32 == f32`
- `f32 > f32`
- `f32 < f32`

and won't be available until these intrinsics:
- `__aeabi_dcmpeq`
- `__aeabi_dcmpgt`
- `__aeabi_dcmple`
- `__aeabi_dcmplt`
- `__aeabi_fcmpeq`
- `__aeabi_fcmpgt`
- `__aeabi_fcmple`
- `__aeabi_fcmplt`

are ported to Rust because compiler-rt doesn't provide an implementation of these for the `thumbv6m-none-eabi` target.

**Comment by hug-dev** [comment]
Should this now be closed?
#276 removed the `thumbv6m` config from the intrinsics example.

**Comment by AaronKutch** [comment]
This should be closed by now
